In [6]:
import pandas as pd
df=pd.read_csv('data 4(asia).csv')
df

GeoAreaName     2011     2012     2013     2014  \
0         Central and Southern Asia   50.008   51.605   53.434   58.045   
1                      Central Asia  186.444  187.972  192.724  197.254   
2    Eastern and South-Eastern Asia  151.303  169.470  198.222  224.897   
3                      Eastern Asia  188.427  210.990  248.897  285.375   
4  Northern Africa and Western Asia   79.453   84.734   91.760   97.654   
5                South-Eastern Asia   60.577   68.693   76.051   80.057   
6                     Southern Asia   44.990   46.570   48.267   52.855   
7                      Western Asia  119.708  129.251  142.033  152.396   

      2015     2016     2017     2018  
0   61.378   67.453   75.195   82.962  
1  195.183  193.246  191.718  195.910  
2  256.608  286.602  323.310  357.960  
3  328.201  368.596  420.719  469.257  
4  105.899  111.654  121.274  132.434  
5   86.244   92.693   94.329   97.886  
6   56.365   62.717   70.787   78.669  
7  166.990  177.467  193.598  209.238

In [2]:
a=df.iloc[:,1:].to_numpy()
print("Matrix:")
print(a)

Matrix:
[[ 50.008  51.605  53.434  58.045  61.378  67.453  75.195  82.962]
 [186.444 187.972 192.724 197.254 195.183 193.246 191.718 195.91 ]
 [151.303 169.47  198.222 224.897 256.608 286.602 323.31  357.96 ]
 [188.427 210.99  248.897 285.375 328.201 368.596 420.719 469.257]
 [ 79.453  84.734  91.76   97.654 105.899 111.654 121.274 132.434]
 [ 60.577  68.693  76.051  80.057  86.244  92.693  94.329  97.886]
 [ 44.99   46.57   48.267  52.855  56.365  62.717  70.787  78.669]
 [119.708 129.251 142.033 152.396 166.99  177.467 193.598 209.238]]


In [5]:
import numpy as np 
x0=np.array([[1],[1],[1],[1],[1],[1],[1],[1]])
j=1
#first iteration
x1=np.matmul(a,x0)
previous_eigen_value=np.round(max([abs(i) for i in x1]),4)
x1=x1/previous_eigen_value
print("Step",j,":",'\n',x1,'\n',"Eigen Value : ",previous_eigen_value)
j+=1
#second iteration
x3=np.matmul(a,x1)
present_eigen_value=np.round(max([abs(i) for i in x3]),4)
x3=np.round(x3/present_eigen_value,4)
print("Step",j,":",'\n',x3,'\n',"Eigen Value : ",present_eigen_value)
#while loop
while(previous_eigen_value!=present_eigen_value):#will calculate until previous and present eigen value are same
    j+=1
    previous_eigen_value=present_eigen_value
    x1=np.matmul(a,x3)
    present_eigen_value=np.round(max([abs(i) for i in x1]),4)
    x1=x1/present_eigen_value
    print("Step",j,"\n",x1,'\n',"Eigen Value : ",present_eigen_value)
    x3=x1

Step 1 : 
 [[0.19840807]
 [0.61117803]
 [0.78095682]
 [1.        ]
 [0.32726619]
 [0.26048002]
 [0.18299026]
 [0.51208112]] 
 Eigen Value :  [2520.462]
Step 2 : 
 [[0.2015]
 [0.6421]
 [0.7837]
 [1.    ]
 [0.3348]
 [0.2684]
 [0.1851]
 [0.5224]] 
 Eigen Value :  [1166.7968]
Step 3 
 [[0.20160535]
 [0.64231826]
 [0.78368963]
 [1.        ]
 [0.33485311]
 [0.26846527]
 [0.1851666 ]
 [0.52247413]] 
 Eigen Value :  [1185.7081]
Step 4 
 [[0.2016062 ]
 [0.64231935]
 [0.78368957]
 [1.00000002]
 [0.33485362]
 [0.26846507]
 [0.18516744]
 [0.52247467]] 
 Eigen Value :  [1185.8757]
Step 5 
 [[0.2016062 ]
 [0.64231933]
 [0.78368956]
 [1.        ]
 [0.33485361]
 [0.26846506]
 [0.18516744]
 [0.52247466]] 
 Eigen Value :  [1185.8768]
Step 6 
 [[0.20160619]
 [0.64231931]
 [0.78368954]
 [0.99999998]
 [0.33485361]
 [0.26846505]
 [0.18516744]
 [0.52247465]] 
 Eigen Value :  [1185.8768]
