In [19]:
#reading data
import pandas as pd
df=pd.read_csv('primary_energy_intensity.csv')
df.index=range(1,7)
df

Continent  2017
1            Africa  5.65
2              Asia  5.03
3         Australia  4.82
4            Europe  4.39
5  Northern America  5.30
6     South America  3.93

In [20]:
#converting data into required matrix
import pandas as pd
import numpy as np
en_rank = pd.read_csv("Primary_intensity_ranking.csv")
df = pd.DataFrame(en_rank)
df.index=range(1,7)
df

Unnamed: 0  Africa  Asia  Australia  Europe  Northen America  \
1            Africa       0     2          2       2                2   
2              Asia       1     0          2       2                1   
3         Australia       1     1          0       2                1   
4            Europe       1     1          1       0                1   
5  Northern America       1     2          2       2                0   
6     South America       1     1          1       1                1   

   South America  
1              2  
2              2  
3              2  
4              2  
5              2  
6              0

In [21]:
#converting data frame into matrix
a=df.iloc[:,1:].to_numpy()
print("Matrix:")
print(a)

Matrix:
[[0 2 2 2 2 2]
 [1 0 2 2 1 2]
 [1 1 0 2 1 2]
 [1 1 1 0 1 2]
 [1 2 2 2 0 2]
 [1 1 1 1 1 0]]


In [27]:
#calculating eigen value and eigen vector
import numpy as np 
x0=np.array([[1],[1],[1],[1],[1],[1]])
j=1
#first iteration
x1=np.matmul(a,x0)
previous_eigen_value=np.round(max([abs(i) for i in x1]),4)
x1=x1/previous_eigen_value
print("Step",j,":",'\n',x1,'\n',"Eigen Value : ",previous_eigen_value)
j+=1
#second iteration
x3=np.matmul(a,x1)
present_eigen_value=np.round(max([abs(i) for i in x3]),4)
x3=np.round(x3/present_eigen_value,4)
print("Step",j,":",'\n',x3,'\n',"Eigen Value : ",present_eigen_value)
#while loop
while(previous_eigen_value!=present_eigen_value):#will calculate until previous and present eigen value are same
    j+=1
    previous_eigen_value=present_eigen_value
    x1=np.matmul(a,x3)
    present_eigen_value=np.round(max([abs(i) for i in x1]),4)
    x1=x1/present_eigen_value
    print("Step",j,"\n",x1,'\n',"Eigen Value : ",present_eigen_value)
    x3=x1

Step 1 : 
 [[1. ]
 [0.8]
 [0.7]
 [0.6]
 [0.9]
 [0.5]] 
 Eigen Value :  [10]
Step 2 : 
 [[1.    ]
 [0.7857]
 [0.7   ]
 [0.6286]
 [0.8857]
 [0.5714]] 
 Eigen Value :  [7.]
Step 3 
 [[1.        ]
 [0.79600437]
 [0.71000168]
 [0.63199306]
 [0.89200314]
 [0.56000448]] 
 Eigen Value :  [7.1428]
Step 4 
 [[1.00000187]
 [0.79331498]
 [0.70640704]
 [0.62925044]
 [0.8908088 ]
 [0.56128165]] 
 Eigen Value :  [7.18]
Step 5 
 [[1.00000361]
 [0.79371817]
 [0.70722132]
 [0.63013585]
 [0.89087141]
 [0.56125761]] 
 Eigen Value :  [7.1621]
Step 6 
 [[1.00000122]
 [0.79371855]
 [0.70710261]
 [0.62992991]
 [0.89091727]
 [0.56122326]] 
 Eigen Value :  [7.1664]
Step 7 
 [[0.99999765]
 [0.79369087]
 [0.70710086]
 [0.62996262]
 [0.89089144]
 [0.56123106]] 
 Eigen Value :  [7.1658]
Step 8 
 [[0.99999354]
 [0.79369759]
 [0.70710421]
 [0.62995659]
 [0.89089404]
 [0.56122742]] 
 Eigen Value :  [7.1658]
