In [7]:
import pandas as pd
df=pd.read_csv('data 3(africa).csv')
df

GeoAreaName  2014  2015  2016  2017  2018
0          Central African Republic     5     5     5     5     5
1                   Northern Africa    88    89    89    90    90
2  Northern Africa and Western Asia    91    91    91    91    91
3                      South Africa    82    83    84    85    85
4                Sub-Saharan Africa    13    13    14    14    15

In [8]:
a=df.iloc[:,1:].to_numpy()
print("Matrix:")
print(a)

Matrix:
[[ 5  5  5  5  5]
 [88 89 89 90 90]
 [91 91 91 91 91]
 [82 83 84 85 85]
 [13 13 14 14 15]]


In [9]:
import numpy as np 
x0=np.array([[1],[1],[1],[1],[1]])
j=1
#first iteration
x1=np.matmul(a,x0)
previous_eigen_value=np.round(max([abs(i) for i in x1]),4)
x1=x1/previous_eigen_value
print("Step",j,":",'\n',x1,'\n',"Eigen Value : ",previous_eigen_value)
j+=1
#second iteration
x3=np.matmul(a,x1)
present_eigen_value=np.round(max([abs(i) for i in x3]),4)
x3=np.round(x3/present_eigen_value,4)
print("Step",j,":",'\n',x3,'\n',"Eigen Value : ",present_eigen_value)
#while loop
while(previous_eigen_value!=present_eigen_value):#will calculate until previous and present eigen value are same
    j+=1
    previous_eigen_value=present_eigen_value
    x1=np.matmul(a,x3)
    present_eigen_value=np.round(max([abs(i) for i in x1]),4)
    x1=x1/present_eigen_value
    print("Step",j,"\n",x1,'\n',"Eigen Value : ",present_eigen_value)
    x3=x1

Step 1 : 
 [[0.05494505]
 [0.98021978]
 [1.        ]
 [0.92087912]
 [0.15164835]] 
 Eigen Value :  [455]
Step 2 : 
 [[0.0549]
 [0.9816]
 [1.    ]
 [0.923 ]
 [0.1507]] 
 Eigen Value :  [282.8]
Step 3 
 [[0.05494505]
 [0.98162162]
 [1.        ]
 [0.92301439]
 [0.15071643]] 
 Eigen Value :  [283.0282]
Step 4 
 [[0.05494505]
 [0.98162136]
 [0.9999999 ]
 [0.92301401]
 [0.15071634]] 
 Eigen Value :  [283.0371]
Step 5 
 [[0.05494505]
 [0.98162144]
 [0.99999998]
 [0.92301408]
 [0.15071635]] 
 Eigen Value :  [283.037]
Step 6 
 [[0.05494506]
 [0.98162152]
 [1.00000007]
 [0.92301416]
 [0.15071636]] 
 Eigen Value :  [283.037]
